import { Redirect } from "@/utilities/redirect";
import Head from "next/head";

const RedirectPage = () => {
  return <>
    <Head>
      <meta name="robots" content="noindex" />
    </Head>
    <Redirect/>
  </>
}
export default RedirectPage;

// import Head from "next/head";
// import { Inter } from "next/font/google";
// import { useTranslation } from "next-i18next";

// const inter = Inter({ subsets: ["latin"] });

// export default function Home() {
//   const { t } = useTranslation();
//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main className={`${inter.className}`}>
//         Hello, not indeyka! {t("AR_T")}
//       </main>
//     </>
//   );
// }
